// Amenity name → lucide icon. Mirrors frontend/src/components/common/
// AmenityIcon.jsx — this lucide-react-native version uses the newer icon
// names (WavesLadder, Funnel, CircleQuestionMark), hence the few renames.
import {
  Wifi, SquareParking, Wind, ArrowUpDown, Dumbbell, Camera, Zap, CookingPot,
  WashingMachine, PawPrint, ShieldCheck, WavesLadder, Flame, Droplet, DoorOpen, Trees,
  Building2, PhoneCall, Droplets, CloudRain, Funnel, Container, Baby, Footprints,
  ShieldAlert, Tv, Refrigerator, Sofa, Bed, DoorClosed, UtensilsCrossed, Microwave,
  Sun, BatteryCharging, Fan, CircleQuestionMark, CarFront, ChefHat, Fence, Coffee,
  Utensils, Sparkles, LampDesk, ShowerHead, Layers, Signpost, Route, LandPlot,
  BrickWall, Sunrise, Hammer, Laptop, TreePalm, PanelBottomClose,
  Accessibility, Video, Bike, Gamepad2, Trophy, PartyPopper, Trash2,
} from 'lucide-react-native'

const ICONS = {
  'WiFi':                 Wifi,
  'Parking':              SquareParking,
  'AC':                   Wind,
  'Lift':                 ArrowUpDown,
  'Gym':                  Dumbbell,
  'CCTV':                 Camera,
  'Power Backup':         Zap,
  'Kitchen':              CookingPot,
  'Washing Machine':      WashingMachine,
  'Pet Friendly':         PawPrint,
  'Security Guard':       ShieldCheck,
  'Swimming Pool':        WavesLadder,
  'Gas Pipeline':         Flame,
  'Geyser':               Droplet,
  // Retired/alias names — NOT in prisma/amenities.js (one concept, one name).
  // Kept so any listing created before 2026-07-17 still renders a real icon
  // instead of the fallback until its rows are remapped.
  'Piped Gas':            Flame,
  'Gated Security':       ShieldCheck,
  'Hot Water':            Droplet,
  'Balcony':              DoorOpen,
  'Terrace':              DoorOpen,
  'Garden':               Trees,
  'Club House':           Building2,
  'Intercom':             PhoneCall,
  'Water Supply':         Droplets,
  'Rainwater Harvesting': CloudRain,
  'Water Purifier':       Funnel,
  'Water Tank':           Container,
  'Play Area':            Baby,
  'Jogging Track':        Footprints,
  'Visitor Parking':      SquareParking,
  'Fire Safety':          ShieldAlert,
  'Laundry':              WashingMachine,
  'TV':                   Tv,
  'Fridge':               Refrigerator,
  'Sofa':                 Sofa,
  'Bed':                  Bed,
  'Wardrobe':             DoorClosed,
  'Dining Table':         UtensilsCrossed,
  'Microwave':            Microwave,
  'Solar Panel':          Sun,
  'EV Charging':          BatteryCharging,
  'Air Cooler':           Fan,
  'Covered Parking':      CarFront,
  'Modular Kitchen':      ChefHat,
  'Gated Community':      Fence,
  'Borewell':             Droplet,
  'Solar Water Heater':   Sun,
  'Servant Room':         Bed,
  'Breakfast':            Coffee,
  'Lunch':                UtensilsCrossed,
  'Dinner':               Utensils,
  'Housekeeping':         Sparkles,
  'Study Desk':           LampDesk,
  'Attached Bath':        ShowerHead,
  'Washroom':             ShowerHead,
  '3-Phase Power':        Zap,
  'Roll-down Shutter':    PanelBottomClose,
  'Mezzanine':            Layers,
  'Signage Space':        Signpost,
  'Near Main Road':       Route,
  'Corner Plot':          LandPlot,
  'Boundary Wall':        BrickWall,
  'East Facing':          Sunrise,
  'Ready to Build':       Hammer,
  'Workspace':            Laptop,
  'Beachfront':           TreePalm,
  'Furnished':            Sofa,
  // Added 2026-07-17 alongside the amenity expansion.
  'Wheelchair Accessible': Accessibility,
  'Video Door Phone':      Video,
  'Two-wheeler Parking':   Bike,
  'Indoor Games':          Gamepad2,
  'Badminton Court':       Trophy,
  'Party Hall':            PartyPopper,
  'Creche':                Baby,
  'Waste Management':      Trash2,
}

const FALLBACK = CircleQuestionMark

export function AmenityIcon({ name, size = 14, color }) {
  const IconCmp = ICONS[name] ?? FALLBACK
  return <IconCmp size={size} color={color} strokeWidth={1.9} />
}
