/**
 * Frontend GeoJSON drift guard.
 *
 * frontend/src/data/layers/metro-lines.json is a checked-in build artifact
 * derived from backend/src/data/metro-lines/*.json. Before the engine, it was
 * regenerated by manually re-running a script — forget, and the web map
 * silently renders stale data while mobile (which reads the source files via
 * the API) shows the truth. This test makes that a red build instead.
 */

import { describe, it, expect } from 'vitest'
import { readFileSync } from 'fs'
import { buildMetroGeoJson } from '../../src/metro-engine/export/geojson.js'
import { loadShippedCities } from '../../src/metro-engine/store.js'
import { FRONTEND_GEOJSON_FILE } from '../../src/metro-engine/paths.js'

describe('frontend GeoJSON drift', () => {
  it('checked-in metro-lines.json matches a fresh export of the shipped source files — run `node scripts/metro-engine.mjs export` if this fails', () => {
    const checkedIn = JSON.parse(readFileSync(FRONTEND_GEOJSON_FILE, 'utf-8'))
    const fresh = buildMetroGeoJson(loadShippedCities())
    expect(checkedIn).toEqual(fresh)
  })
})
